### ISSUE TITLE
can't paste hash key

### ISSUE THREAD

**Issue by michalprynych** [jameshulse/sc2replayuploader#2]
Hey, I'm on High Sierra (10.13.2 (17C88)) and I can't paste the hash key. I have to write it manually there.

**Comment by jameshulse** [comment]
Thats annoying! I'll take a look and see if I can get a fix out today.

**Comment by jameshulse** [comment]
Try release v0.5.1 and let me know how you get on.

**Comment by michalprynych** [comment]
works now, thanks!

**Comment by jameshulse** [comment]
No problem. Let me know if you run in to any more problems.
